{% set version = "1.2.45" %}

package:
  name: survex
  version: {{ version }}

source:
  url: https://survex.com/software/{{ version }}/survex-{{ version }}.tar.gz

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}     # [linux]

  host:
    - proj4 4.*

    # for aven
    - wxwidgets
    - ffmpeg 4.*
    - libglu

about:
  home: https://survex.com/
  summary: 'cave surveying and mapping software'
  license: GPL-2

test:
  commands:
    - cavern --version | grep -q {{ version }}
    - aven --version | grep -q {{ version }}
